language: node_js
node_js: lts/fermium
env:
  global:
    - HUSKY = 0

jobs:
  include:
    - stage: Validations
      script: npm run lint
      name: Linting with ESLint
    - script: npm run format:check
      name: Check format with prettier
    - stage: Build and Test
      script: npm run build
      name: Building commonjs modules
    - script: npm t
      name: Testing with Jest

    - stage: Deploy
      name: Deploying to npm
      deploy:
        provider: npm
        email: "${NPM_EMAIL}"
        api_key:
          secure: "${NPM_TOKEN}"
        on:
          repo: peterleiva/webpack-config-organizer
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(main|canary)$
        skip_cleanup: true

notifications:
  slack:
    rooms:
      - secure: sInf4pKMWpiwzPnDaRDECKZ0ZaIdwAwV847cZuQdWwF6+rhAGziXvprlJ7H3JNrrTUy4W/I85PBPqFwCkGtpmnmN50lFtaHqDJvl2d3KJcEqA4hngIwgWPyVLER5zMjltrCHILjBd0d2Z1ad5mKmbw/fnV9tWOXcTM6PKxCF6r8N5TxWmpJVpIFQmtuHa7ojDxourCesOPRK6i1io86cMs+fLEUwn6ymjtQ7TKlcSWEIr+0bKZHoTeRNNwpD5klCkRR5rEKuDmU7+DfgYhtDoIT+xYR0PiTVucBwdyyidyNdO33c2sumM3tqb8wYIHXMUPeeAku8bXMfnKjKqai5GmW8F2nPkJTl6wLYzRY+xwc44Piw1lTd75nYRvCDqogpoc5Nd4L/AAkPn1hzxoyUe1lew5D4EWSZcfdzglbMDQnhoAOKYKTC3kDXYlqESSHzGpWxgtZPqZhoVUywlGgtVjRLGP8G6C+aYAgRKpujmYlfydrp2WAaHvbU/TDjTAH0ClOWhjdVolSRil5alg1TomMUBbSiT2/3v9yM56tddYj8pYxmvfOsEacwqzngX3KpoDctMj+3sD+nJpnQLcw/Wqw85IpVyHezYiMZV1z9GyGYRhCrsb6EDWBcZUAZtoTkOtcdiy5Dq78z4IZu6SGCPuzrPpeEwD84duBX8XOfic8=
      - secure: m6xir8PwYwpSOKmUIkqYqM/Uvo2GGr1QiEg2ZZ9E4Tep36k0JaBQ43bx8WEK2LeoZf8uqIuK2Z0utPeF8GGcjhiqEh8l2P6Bqxlm3ip2ZJE9rCEMFZv8hnDe4HqdJ9BrMKIFKyfdPEkJkzfR8WQ/Ngwx9sT2JND8uiCV/K7piWe/1WlN/KuVMJRgGUepu5CpLYxD89z7bGos3OUlxGY5pZ0kPDtJQduLv/v/TnokUTT/N35wFd0zt4+XP6OOdgUOP/ayquO93TzvGrRmjUXj37d7Vwr0FAtu4EQizG6C2A4Cr0EpuYC00XdXsSKUgZqpxNFu6Uz5a4D3J6vvTGJgEzxzAFqMr+nFYsIcWHsc6/60qKh0GFqqibQAbvjT6TYvwn3Wn619ncANgCDJtyyAaXyIDkgmTouZ2/CX5t7Ndg+uIwgd5/XC2viygX43XLbBnc5YvSUwY6pLvZWbUYrWrFwJkpNyGYgjrU6XYbFubg4vNgpxRGfBieEEV//TlDz+nEoxqYCp3OsXieff+L+DRrMKcJoBNIlGrZHvHvswLvAb0j6ry7u9geJNUzfqSrxhEtU2JtORxdyOfmLGttODGxhDAePxPK6L7AYnE1YsnRoVfEqrpn5yrKhR2tYHEx0PVcFmhw2qcB54VtklN50T2JCIkyMtB6n2QgmMeZrxZ/I=
